/**
 * Centralized domain status enums (database + API contract).
 * @see docs/04-database-design.md §C
 */

export const APPOINTMENT_STATUSES = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  NO_SHOW: "NO_SHOW",
} as const;

export type AppointmentStatus =
  (typeof APPOINTMENT_STATUSES)[keyof typeof APPOINTMENT_STATUSES];

export const APPOINTMENT_STATUS_VALUES = [
  APPOINTMENT_STATUSES.PENDING,
  APPOINTMENT_STATUSES.CONFIRMED,
  APPOINTMENT_STATUSES.COMPLETED,
  APPOINTMENT_STATUSES.CANCELLED,
  APPOINTMENT_STATUSES.NO_SHOW,
] as const;

export const SLOT_STATUSES = {
  AVAILABLE: "AVAILABLE",
  BOOKED: "BOOKED",
  BLOCKED: "BLOCKED",
  HOLIDAY: "HOLIDAY",
} as const;

export type SlotStatus = (typeof SLOT_STATUSES)[keyof typeof SLOT_STATUSES];

export const SLOT_STATUS_VALUES = [
  SLOT_STATUSES.AVAILABLE,
  SLOT_STATUSES.BOOKED,
  SLOT_STATUSES.BLOCKED,
  SLOT_STATUSES.HOLIDAY,
] as const;

export const PRESCRIPTION_STATUSES = {
  DRAFT: "DRAFT",
  ISSUED: "ISSUED",
  AMENDED: "AMENDED",
  VOID: "VOID",
  ARCHIVED: "ARCHIVED",
} as const;

export type PrescriptionStatus =
  (typeof PRESCRIPTION_STATUSES)[keyof typeof PRESCRIPTION_STATUSES];

export const PRESCRIPTION_STATUS_VALUES = [
  PRESCRIPTION_STATUSES.DRAFT,
  PRESCRIPTION_STATUSES.ISSUED,
  PRESCRIPTION_STATUSES.AMENDED,
  PRESCRIPTION_STATUSES.VOID,
  PRESCRIPTION_STATUSES.ARCHIVED,
] as const;

export const DOCTOR_STATUSES = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  ON_LEAVE: "ON_LEAVE",
} as const;

export type DoctorStatus =
  (typeof DOCTOR_STATUSES)[keyof typeof DOCTOR_STATUSES];

export const DOCTOR_STATUS_VALUES = [
  DOCTOR_STATUSES.ACTIVE,
  DOCTOR_STATUSES.INACTIVE,
  DOCTOR_STATUSES.ON_LEAVE,
] as const;

export const PATIENT_STATUSES = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  ARCHIVED: "ARCHIVED",
} as const;

export type PatientStatus =
  (typeof PATIENT_STATUSES)[keyof typeof PATIENT_STATUSES];

export const PATIENT_STATUS_VALUES = [
  PATIENT_STATUSES.ACTIVE,
  PATIENT_STATUSES.INACTIVE,
  PATIENT_STATUSES.ARCHIVED,
] as const;

export const CONTENT_STATUSES = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  ARCHIVED: "ARCHIVED",
} as const;

export type ContentStatus =
  (typeof CONTENT_STATUSES)[keyof typeof CONTENT_STATUSES];

export const CONTENT_STATUS_VALUES = [
  CONTENT_STATUSES.DRAFT,
  CONTENT_STATUSES.PUBLISHED,
  CONTENT_STATUSES.ARCHIVED,
] as const;
