/**
 * Internal audit actions for privileged mutations.
 */

export const AUDIT_ACTIONS = {
  ROLE_CHANGED: "ROLE_CHANGED",
  USER_DISABLED: "USER_DISABLED",
  USER_ENABLED: "USER_ENABLED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  DOCUMENT_DELETED: "DOCUMENT_DELETED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_ACTION_VALUES = [
  AUDIT_ACTIONS.ROLE_CHANGED,
  AUDIT_ACTIONS.USER_DISABLED,
  AUDIT_ACTIONS.USER_ENABLED,
  AUDIT_ACTIONS.DOCUMENT_UPLOADED,
  AUDIT_ACTIONS.DOCUMENT_DELETED,
] as const;
